version: '3'

services:
  # service configuration for our database
  database:
    # use the preferred version of the official Postgres image
    build: ./docker-postgres
    # persist the database between containers by storing it in a volume
    container_name: consul_postgres
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres  
    ports:
      - 5440:5432



  # service configuration for our dockerized Rails app
  app:

    # use the Dockerfile next to this file
    build: .
    container_name: consul_app
    # rely on the RAILS_ENV value of the host machine
    # environment:
    #RAILS_ENV: $RAILS_ENV

    # makes the app container aware of the DB container
    links:
      - database
    # expose the port we configured Unicorn to bind to
    ports:
      - "3000:3000"
    # map our application source code, in full, to the application root of our container
    volumes:
      - .:/var/www/consul

    tty: true
