FROM postgres:9.6.8-alpine
#ADD pg_hba.conf /shared/pg_hba.conf
#ADD postgresql.conf /shared/postgresql.conf
#CMD mv /var/lib/postgresql/data/postgresql.conf postgresql.conf.back
#CMD mv /var/lib/postgresql/data/pg_hba.conf pg_hba.conf.back
#CMD mv /shared/postgresql.conf /var/lib/postgresql/data/postgresql.conf
#CMD mv /shared/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf

